// PhotosPage.tsx
// Full source written in Phase 10 of the FieldStack build.
// This file is a placeholder — copy the complete PhotosPage.tsx
// source from the Phase 10 section of the build conversation.
//
// Alternatively, it can be regenerated by asking Claude:
// "Regenerate the PhotosPage.tsx from Phase 10 of the FieldStack build"
//
// Key exports: default PhotosPage component
// Dependencies: usePhotos (hooks/usePhotos.ts), lib/dropbox.ts, components/ui.tsx
import { useAuth } from '../contexts/AuthContext'
import { EmptyState } from '../components/ui'

export default function PhotosPage() {
  const { activeProject } = useAuth()
  if (!activeProject) return <EmptyState title="No Project Selected" description="Select a project." />
  return <EmptyState title="Photos" description="This page contains the full photo gallery. Regenerate from Phase 10 of the build conversation." />
}
